name: sheet
description: A fully customizable draggable bottom sheet.
version: 1.0.0-pre
homepage: https://github.com/jamesblasco/modal_bottom_sheet

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  lints: ^2.0.0

flutter: